### ISSUE TITLE
1.16.0 / 1.16.1 / 1.17.0 : @remix-run/v1-route-convention do not save new route

### ISSUE THREAD

**Issue by raskyer** [remix-run/v1-compat-utils#23] opened 2023-06-07 17:34 UTC
### What version of Remix are you using?

1.17.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- Install 1.17.0
- Configure v2_routeConvention with @remix-run/v1-route-convention
- Run project
- Add a route
- After a very long rebuild time (issue already created before) the route isn't registered

Precision : Do not use the new dev server but the historic one.

### Expected Behavior

The route is registered and accessible without full reload of dev server.

### Actual Behavior

The route is not registered.

**Comment by raskyer** [comment] 2023-07-14 13:56
Is there any update ?

**Comment by brophdawg11** [comment] 2023-08-10 13:21
Can you provide a reproduction?  This works fine for me on a brand new app, you can see in the logs that I created a new file and it was picked up in 91ms. 

Here's the `remix.confg.js`:

```js
const { createRoutesFromFolders } = require("@remix-run/v1-route-convention");

/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  ignoredRouteFiles: ["**/*"],
  serverModuleFormat: "cjs",
  future: {
    v2_dev: false,
    v2_errorBoundary: true,
    v2_headers: true,
    v2_meta: true,
    v2_normalizeFormMethod: true,
    v2_routeConvention: true,
  },
  routes: (defineRoutes) => createRoutesFromFolders(defineRoutes),
};
```

```sh
> remix dev


 💿  remix dev

 warn  The `remix dev` changing in v2
┃ You can use the `v2_dev` future flag to opt-in early.
┃ -> https://remix.run/docs/en/main/pages/v2#dev-server
┗
💿 Building...
💿 Rebuilt in 175ms
Remix App Server started at http://localhost:3000 (http://10.0.0.251:3000)
GET / 200 - - 55.512 ms
💿 File created: app/routes/page.tsx
💿 Rebuilding...
💿 Rebuilt in 91ms
GET / 200 - - 4.885 ms
GET /page 200 - - 11.220 ms
```

**Comment by brophdawg11** [comment] 2023-08-21 20:45
I'm going to close this out due to the lack of a reproduction but if you can prepare one please let us know and we'll get this opened back up.  Thanks!

**Closed by brophdawg11** 2023-08-21 20:45 UTC
Labels: needs-response
